### ISSUE TITLE
[Testing] Create a FIPS requirement for kserve  (Caikit+TGIS)

### ISSUE THREAD

**Issue by tarukumar** [opendatahub-io/kserve#102]
/kind bug

**What steps did you take and what happened:**
As per the requirement we need to test FIPS for kserve( Caikit + tgis ). Below are the requirement received from IBM.

`[Note: Node-to-Node encryption using OVN-Kubernetes network plugin has performance implications. The solution is to throw additional CPU at it and to adjust the MTU site applied and the datagram size being used. However, on AWS EC2-to-EC2 encryption is hardware accelerated and provided by default. This approach provides the needed node-to-node encryption for the FIPS Wall to work. ROSA also provides node-to-node encryption, likely through the same means.]`

**What did you expect to happen:**
Caikit + Tgis stecak should work without any issue

**Comment by tarukumar** [comment]
we can use https://github.com/openshift/check-payload tool to verify  FIPS enabled binaries

**Comment by bdattoma** [comment]
Related: https://github.com/opendatahub-io/caikit-tgis-serving/issues/130

**Comment by israel-hdez** [comment]
Migrated to https://issues.redhat.com/browse/RHOAIENG-2256

/close
