### ISSUE TITLE
[P0] KServe and TGIS runtime exploration

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#11]
Ref: https://issues.redhat.com/browse/RHODS-9169

**Comment by heyselbi** [comment]
@Xaenalt @Jooho @danielezonca is this in exploration phase still?

**Comment by Xaenalt** [comment]
I'd say we are past the exploration phase with docs on how to do a demo deployment at https://github.com/Xaenalt/caikit-serving and https://github.com/Xaenalt/caikit-serving/tree/main/docs/demo/kserve
