### ISSUE TITLE
Need a way to customize kserve configuration

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/kserve#113]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
At the moment, there is no way to customize kserve configuration such as storage-initializer. If we update configmap, it will be rollback by odh operator.

We need a way to customize like what modelmesh did :
https://github.com/opendatahub-io/modelmesh-serving/tree/main/docs/configuration

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by Jooho** [comment]
created internal jira ticket: https://issues.redhat.com/browse/RHOAIENG-1262

**Comment by israel-hdez** [comment]
Closing in favor of tracking via Jira.
