### ISSUE TITLE
Adjust Kserve's python image uid for ODH

### ISSUE THREAD

**Issue by skonto** [opendatahub-io/kserve#13]
/kind feature

**Describe the solution you'd like**
The uid needs to change for python images to something compatible for ODH.
Right now kserve needs to run with uid 1000 for python images because it creates files that have permissions based on that id.
This needs to change as now the user needs to allow uid 1000 on OCP, the latter requires a special scc.
See discussion https://github.com/opendatahub-io/odh-manifests/pull/838#discussion_r1236922732 for more.

**Anything else you would like to add:**
N/A

**Comment by skonto** [comment]
cc @danielezonca

**Comment by ReToCode** [comment]
I don't think it is as you do not target/support those runtimes, rigth?

But, it would be if you want to support the runtimes that KServe has. KServe runtimes run as uid=1000 which will not work on OCP without anyuid. But images can be rebuilt with another use if necessary.

**Comment by israel-hdez** [comment]
Reducing priority to `minor`, and ejecting from Sprint.
