### ISSUE TITLE
[P0] Create KServe community images

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#2]

**Comment by israel-hdez** [comment]
KServe community images:
* v0.10.2 tag - `podman pull quay.io/opendatahub/kserve-controller:v0.10.2`
* main branch - `podman pull quay.io/opendatahub/kserve-controller:latest`

**Comment by israel-hdez** [comment]
agent images:
* v0.10.2 tag - `podman pull quay.io/opendatahub/kserve-agent:v0.10.2`
* main branch - `podman pull quay.io/opendatahub/kserve-agent:latest`
router images:
* v0.10.2 tag - `podman pull quay.io/opendatahub/kserve-router:v0.10.2`
* main branch - `podman pull quay.io/opendatahub/kserve-router:latest`

**Comment by israel-hdez** [comment]
Explainer and storage initializer images:

* v0.10.2 tag
  * podman pull quay.io/opendatahub/kserve-alibi-explainer:v0.10.2
  * podman pull quay.io/opendatahub/kserve-storage-initializer:v0.10.2
* main branch
  * podman pull quay.io/opendatahub/kserve-alibi-explainer:latest
  * podman pull quay.io/opendatahub/kserve-art-explainer:latest
  * podman pull quay.io/opendatahub/kserve-storage-initializer:latest

**Comment by israel-hdez** [comment]
I'll close as completed. If any image needs to be rebuilt, I'll do it as part of some other ticket.
