### ISSUE TITLE
[P0] SPIKE Define and document the end to end request flow for a request

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#20]

**Comment by heyselbi** [comment]
@danielezonca please provide your updates here for different scenarios of user workflow.

**Comment by danielezonca** [comment]
KServe LLM model serving

![Image](https://github.com/opendatahub-io/kserve/assets/244607/d9040d88-7448-43b0-9756-c909504f6935)


Other scenarios (ModelMesh / Prompt Tuning / RawDeployment)


![Image](https://github.com/opendatahub-io/kserve/assets/244607/5221c2da-acac-40b2-8e93-96667a8377dc)
