### ISSUE TITLE
[P0] Users must be able to deploy an updated version of a foundation model

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#24]
From req doc:
For example, if using a curated IBM model, when IBM releases a new model version, users must be able to deploy the updated model version. The same scenario applies to foundation models from other sources such as Hugging Face.

**Comment by Xaenalt** [comment]
Clarification on the intent here, is this intended to be something where IBM (or HuggingFace, other registry, etc) pushes an update to their model, and it is force-pushed to all users? Or is the intent just to have the ability to update a deployed InferenceService with a new version of a model?

**Comment by taneem-ibrahim** [comment]
@Xaenalt 

>  is the intent just to have the ability to update a deployed InferenceService with a new version of a model? 
It is this one.

**Comment by bdattoma** [comment]
how the update will be rollout?

**Comment by heyselbi** [comment]
Closing this because it is worked on in here: https://github.com/opendatahub-io/kserve/issues/40
