### ISSUE TITLE
Document annotation for namespaces with `anyuid` enbled

### ISSUE THREAD

**Issue by israel-hdez** [opendatahub-io/kserve#25]
In pull request #18 it was introduced some code to automatically set the UID of the storage-initializer container, so that it runs properly when using Maistra and OpenShift.

For namespaces that forbid running containers with `anyuid`, the mesh sidecar runs with the project allowed range +1. For namespaces that alloq running containers with `anyuid`, the mesh sidecar runs with `1337` uid. 

The controller always assumes that `anyuid` is forbidden. So, if the namespace enabled `anyuid`, the storage-initializer may still fail. However, the end-user can still override which UID is used [via an annotation](https://github.com/opendatahub-io/kserve/pull/18#issuecomment-1632272504) and this can be used as a workaround. Some documentation should state this.

**Comment by Xaenalt** [comment]
@israel-hdez Is this still needed or has the anyuid fix now made this issue obsolete?

**Comment by israel-hdez** [comment]
Related upstream PR: https://github.com/kserve/kserve/pull/3316.
If the upstream PR is accepted, changes in #18 can be reverted and we can drop this ticket.

cc @ReToCode @skonto

**Comment by israel-hdez** [comment]
Closing, because kserve/kserve#3316 was accepted, and this is no longer needed.
