### ISSUE TITLE
Enhance UID selection for storage-initializer container

### ISSUE THREAD

**Issue by israel-hdez** [opendatahub-io/kserve#26]
The changes introduced in pull request #18 are a workaround until Maistra introduces enhancements to let initContainers run smoothly.

As noted in these two comments of the pull request:
* https://github.com/opendatahub-io/kserve/pull/18#issuecomment-1632272504
* https://github.com/opendatahub-io/kserve/pull/18#issuecomment-1633121834

the selection of the UID could be enhanced to be more automatic, removing the need to manually set annotations, and also removing the need of the documentation stated at #25.

If the workaround of #18 becomes permanent, the suggested enhancements should be applied.

**Comment by taneem-ibrahim** [comment]
istio tracker: https://github.com/istio/istio/pull/45394

**Comment by israel-hdez** [comment]
Related upstream PR: https://github.com/kserve/kserve/pull/3316.
If the upstream PR is accepted, changes in #18 can be reverted to close this ticket.

**Comment by israel-hdez** [comment]
Moved to: https://issues.redhat.com/browse/RHOAIENG-1007
