### ISSUE TITLE
[P0] Update "Sync Upstream" template with tasks related to KServe

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#3]
Ref: https://issues.redhat.com/browse/RHODS-8928

**Comment by heyselbi** [comment]
@Jooho did we do it this sprint? or should it be moved to next sprint?

**Comment by taneem-ibrahim** [comment]
@vaibhavjainwiz could you please put an estimated start and end date?

**Comment by vaibhavjainwiz** [comment]
done. I had updated template in github issue.
https://github.com/opendatahub-io/modelmesh-serving/issues/122
