### ISSUE TITLE
CPaaS onboarding of KServe

### ISSUE THREAD

**Issue by vaibhavjainwiz** [opendatahub-io/kserve#30]

**Comment by heyselbi** [comment]
Vaibhav's PR: https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/911

**Comment by vaibhavjainwiz** [comment]
KServe build through CPaaS is currently blocked because pre-built wheel library are not allowed to use in CPaaS and using other ways to fix this issue would require to change application code drastically for a sub-dep. Which would be hard to maintain.

**Comment by heyselbi** [comment]
@taneem-ibrahim @vaibhavjainwiz could you provide update on this? I believe we can close this one right?

**Comment by vaibhavjainwiz** [comment]
KServe build through CPaaS is currently blocked. For 1.31 release team has decided to go with openshift-ci images. 
We would try to fix CPaaS issue in next sprint.

**Comment by vaibhavjainwiz** [comment]
Because of Kserve build issue in CPaaS,`check-patch` test is failing for all PRs in RHODS CPaaS. As discussed with @dchourasia there is no way to skip kserve build from `check-patch` stage so we have decided to revert the kserve changes from CPaaS for now so that `check-patch` could work and later add them when required.

https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1692686880438789?thread_ts=1692684569.839469&cid=C05NXTEHLGY

**Comment by israel-hdez** [comment]
Closing as won't do. It's been decided that we'll use CPaaS successor.
