### ISSUE TITLE
Setup odh-nightlies for KServe

### ISSUE THREAD

**Issue by vaibhavjainwiz** [opendatahub-io/kserve#34]

**Comment by vaibhavjainwiz** [comment]
raised below PR : https://gitlab.cee.redhat.com/data-hub/rhods-live-builder/-/merge_requests/228

**Comment by vaibhavjainwiz** [comment]
This issue on hold. First we need to figure out on which branch we want to enable nightlies build.

**Comment by israel-hdez** [comment]
Similarly to #30 , this is not going to be done.
