### ISSUE TITLE
Source of images on quay.io/opendatahub

### ISSUE THREAD

**Issue by npanpaliya** [opendatahub-io/kserve#392]
The build and push jobs of multi-arch images of kserve like kserve-agent, router, qpext or kserve-controller have been failing for some time. And since the build jobs are failing, ideally there should not be any image on quay.io for the newer tags like v0.12.1.2, or v0.12.1.3. But I see there are amd64 specific tags available but not for ppc64le/s390x/arm64 etc. So, I want to know how these images are built and pushed to quay.io even after GH workflows are failing.

**Comment by israel-hdez** [comment]
We have openshift-ci (you may have seen it in GitHub checks in PRs), which is also doing builds.
Configuration file is here: https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/kserve/opendatahub-io-kserve-master.yaml.

It only builds amd64 images. I don't know if it is capable of building other architectures.
GitHub actions workflows (which surely can build for other architectures) were broken until you kindly fixed :-)

**Comment by israel-hdez** [comment]
OK, I'm closing this as looks solved.
Please, re-open if needed.
