### ISSUE TITLE
SMMR(Service Mesh Member Roll) need to be updated for each namespace

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/kserve#41]
/kind feature

**Describe the solution you'd like**
Kserve serverless mode use istio so if a namespace deploy model with kserve, the namespace must be added to SMMR. But normal users can not update SMMR due to permission issues. For this reason, they need to ask cluster administrators.

There are several ways to fix this:
- [Give a editable permission to users](https://docs.openshift.com/rosa/service_mesh/v2x/ossm-profiles-users.html)
- [Use memberSelector](https://docs.openshift.com/container-platform/4.11/service_mesh/v2x/ossm-create-mesh.html#ossm-adding-project-using-label-selectors-cli_ossm-create-mesh)
- Manage it by an operator

**Comment by heyselbi** [comment]
Scope level: we need to have at least a documentation for 1.32

**Comment by heyselbi** [comment]
@VedantMahabaleshwarkar odh-model-controller already implements that.
