### ISSUE TITLE
ServingRuntime Template

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/kserve#42]
/kind feature

**Describe the solution you'd like**
ODH KServe does not include `clusterServingRuntime` and it only supports namespace-scope ServingRuntime. So `ServingRuntime` needs to be created in a namespace. In order to create a consistent ServingRuntime, `Template` would be a good option. In addition, doc needs to be updated on how to use the create ServingRuntime using Template for the target namespace.

**Comment by heyselbi** [comment]
Current scope: documentation-level only

**Comment by Jooho** [comment]
PR sent: https://github.com/opendatahub-io/caikit-tgis-serving/pull/49
