### ISSUE TITLE
Setup GitHub action to automate process to update odh-manifest for kserve

### ISSUE THREAD

**Issue by vaibhavjainwiz** [opendatahub-io/kserve#56]
Setup GitHub action to automate the process of PR generation on odh-manifest to update kserve images references generated by openshift-ci.

reference : https://github.com/red-hat-data-services/odh-manifests/actions/runs/5687063188

**Comment by israel-hdez** [comment]
Archival of `odh-manifests` repository is expected to be done quite soon.

It is no longer worth to spend time on automation that would be retired in the very short term.
Let's stick to updating manually, while the transition to per-repo manifests is finished.

Closing as `won't fix`.
