### ISSUE TITLE
[P1] (optional) Test RawDeployment

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#6]
**Goal:**
The goal of the ticket is to create an alternative configuration option (additional KfDef or a parameter) to install/configure KServe in OpenShift via ODH to use plain k8s `Deployment` (aka `RawDeployment` mode).

**More context:**
The default deployment mechanism for KServe is using [Knative and Istio](https://kserve.github.io/website/0.10/admin/serverless/serverless/) but it is also possible to configure KServe to create plain `Deployment` object using [`RawDeployment` mode](https://kserve.github.io/website/0.10/admin/kubernetes_deployment/).

@RetoCode did already an experiment using RawDeployment in OpenShift (see [`POC_RAW_DEPLOYMENTS.md`](https://github.com/ReToCode/knative-kserve/blob/main/POC_RAW_DEPLOYMENTS.md)) so it should work.

**Comment by heyselbi** [comment]
@danielezonca could we add more details here? Or please tag someone who can.

**Comment by skonto** [comment]
Probably you want to use https://github.com/opendatahub-io/kserve/issues/5 to test on a separate job.

**Comment by danielezonca** [comment]
I agree with @skonto comment

@israel-hdez 
Is it fine to assign this task to you?
Implementing #5 you should be able to enable the e2e test suite and if this covers also the RawDeployment, this ticket is automatically solved, if it doesn't (or there are issues to enable this test case) fine for me to move to 1.32 sprint.
Wdyt?

**Comment by israel-hdez** [comment]
I do agree that we can use the e2e suite to cover this ticket. And I'm OK assigning this one to me.

To keep work focused, I prefer to keep this open. On #5 I'm focused on Serverless. For RawDeployment, another cluster needs to be provisioned to run the tests. So, it is two different _jobs_/tasks.

**Comment by heyselbi** [comment]
@israel-hdez could you update the Expected end date accordingly, based on your best estimation?

**Comment by israel-hdez** [comment]
> @israel-hdez could you update the Expected end date accordingly, based on your best estimation?

I updated it to august 18.

**Comment by israel-hdez** [comment]
Upstream already covers `RawDeployment`, while in ODH we are not supporting this deployment mode yet.

For now, we will trust upstream would check correctness of RawDeployment (there are already itests). If, in the future, we have the need to support RawDeployment in ODH, we will revisit this feature.

Closing, for now.
