### ISSUE TITLE
Update KServe to v0.11 in RHODS 1.31

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#60]
v0.11 controller was used but the manifest is v0.10. The manifest needs to be updated to v0.11.

@israel-hdez : The failure was because the manifests I initially provided are newer than the RHODS container images. I simply generated manifests that match the already built RHODS container images.

**Comment by heyselbi** [comment]
@vaibhavjainwiz @israel-hdez @Jooho Please provide details and add PRs

**Comment by heyselbi** [comment]
https://github.com/opendatahub-io/odh-manifests/pull/908

**Comment by heyselbi** [comment]
https://github.com/opendatahub-io/kserve/pull/59

**Comment by heyselbi** [comment]
@israel-hdez if this is complete, could you comment and close it out?

**Comment by israel-hdez** [comment]
> @israel-hdez if this is complete, could you comment and close it out?

The PR for odh-manifests is still not merged: https://github.com/opendatahub-io/odh-manifests/pull/908

**Comment by heyselbi** [comment]
PR is merged, issue can be closed.
