### ISSUE TITLE
Do not fail when dependencies are not installed

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/kserve#65]
/kind feature

**Describe the solution you'd like**
Add a dependency check inside the kserve pod in order not to fail when pre-required operators (e.g., Knative, istio/servicemesh) are not installed (and deployed, probably). 
Outcome could be:
- kserve pod not created
- kserve created and reporting a clear error message about what's missing
- others

**Anything else you would like to add:**
Example of error message in KServe logs:
```
I0822 10:17:59.403474       1 request.go:665] Waited for 2.948922744s due to client-side throttling, not priority and fairness, request: GET:[https://172.30.0.1:443/apis/samples.operator.openshift.io/v1?timeout=32s](https://172.30.0.1/apis/samples.operator.openshift.io/v1?timeout=32s)
{"level":"error","ts":1692699480.5086067,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"Service.serving.knative.dev","error":"no matches for kind \"Service\" in version \"serving.knative.dev/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/source/source.go:137\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.9/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.9/pkg/util/wait/wait.go:580\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.9/pkg/util/wait/wait.go:545\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/source/source.go:131"}
```

**Comment by danielezonca** [comment]
I think this ticket should be moved to upstream kserve repo ( https://github.com/kserve/kserve/issues ).
We can keep this as "clone" to simplify the tracking but the solution should be implemented upstream

**Comment by manosnoam** [comment]
Getting `"error":"failed to wait for inferenceservice caches to sync: timed out waiting for cache to be synced"` in kserve-controller-manager, before installing dependencies:
![image](https://github.com/opendatahub-io/kserve/assets/9913945/58afeeb1-69eb-450d-b728-c6dc2ebae698)

Pod log:
[kserve-controller-manager.log](https://github.com/opendatahub-io/kserve/files/12476569/kserve-controller-manager.log)

**Comment by israel-hdez** [comment]
> I think this ticket should be moved to upstream kserve repo ( https://github.com/kserve/kserve/issues ). We can keep this as "clone" to simplify the tracking but the solution should be implemented upstream

Hmmm... It probably depends more on what outcome we want.


> Outcome could be:
> 
>     * kserve pod not created
> 
>     * kserve created and reporting a clear error message about what's missing

If we want the first, I'd think the fix is more on odh-operator side. If we want the 2nd, it can fall on upstream; however upstream have installation steps outlined here: https://kserve.github.io/website/0.11/admin/serverless/serverless/. IMHO, under upstream perspective, failure to install dependencies is user error, because docs make very clear installation steps.

Personally, I lean towards thinking the fix should go to ODH-operator which should not try to install KServe and should make it clear in the `status` field of `DataScienceCluster` that dependencies are missing.

**Comment by israel-hdez** [comment]
> Shall we move this issue in odh-operator repo then?

I'm OK with keeping the issue here, as it requires some coordination between Serving. I'll ping @VaishnaviHire to have a 2nd thought.

> However I wouldn't see it as high priority,

Yes, I agree is not high priority.
