### ISSUE TITLE
Move from odh-manifests to Kserve source repo

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/kserve#72]
/kind feature

**Describe the solution you'd like**
As part of the [transition from central odh-manifests to component repo work](https://github.com/opendatahub-io/opendatahub-operator/issues/338), it would be good to have a placeholder file `params.env` in `kserve/config` folder to host kserve images.
this has previously done in  https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/base/params.env

**Anything else you would like to add:**
Ensure all manifests required by kserve in  https://github.com/opendatahub-io/odh-manifests/tree/master/kserve can be mapped to https://github.com/opendatahub-io/kserve/tree/master/config
i.e running` kustmoize build` in `kserve/config` will produce no less function as run from `odh-manifets/kserve/base `

**Comment by israel-hdez** [comment]
Hey, @zdtsw 

Is `params.env` still going to be the preferred method to parametrize images?

I've heard that it may be going away.

**Comment by zdtsw** [comment]
> Hey, @zdtsw
> 
> Is `params.env` still going to be the preferred method to parametrize images?
> 
> I've heard that it may be going away.

Correct!
I've not heard anything that we plan to move away from `params.env`
for ODH it is not important to have `params.env,` but downstream still will rely on this file.
it is up to team to decide if to keep a placeholder `params.env `in ODH or not.

**Comment by israel-hdez** [comment]
@zdtsw A (basic?) question:

For operator v1, we still needed older kustomize format. So, `odh-manifests` needed to be compatible with the older format.

I understand that for per-repo manifests, which I'm assuming it is only for operator v2, we no longer have that restriction and we can use the very latest kustomize v5 format.

Is this right? Or do we still need to support the older format?

**Comment by zdtsw** [comment]
yes, you are correct
we will still support v1 release for a couple of rounds. and v1 operator need old format of manifests to work with pre-v5 `kustomize build`.

in this case ( till we do not release new version for v1): manifests from kserve (and all components) need to stay with the old syntax.

we will have another "epic" to follow-up the upgrade "manifests" for all components.

**Comment by zdtsw** [comment]
if, you already migrated "manifests" in "kserve" repo for v5 `kustomize`
there is a workaround for v1 operator, but that will require you to keep updating/using "odh-manifests" repo.

e.g:
in "kserve" repo, the manifests are in the new format, this will be used by v2 operator
in "odh-manifests/kserve", you generate v3 compatible manifests for kserve, this will be used by v1 operator.
i would not recommand to do this way, but if that is the case, we can work it out together.

**Comment by zdtsw** [comment]
**sorry, must correct myself.**

in v1 operator, kserve is not supported, only modelmesh is.
so if you migrate manifests in kserve repo for v5 kustomize, it should be fine for v2 operator.

**Comment by heyselbi** [comment]
@israel-hdez could you please attach the PRs updating the SHA tags once they are ready and then close the issue?

**Comment by heyselbi** [comment]
Pending PRs:
https://github.com/opendatahub-io/odh-model-controller/pull/111
https://github.com/opendatahub-io/odh-model-controller/pull/110

**Comment by israel-hdez** [comment]
All done.
