### ISSUE TITLE
Address "High" vulnerabilities in SNYK scans of KServe

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#73]
Check all the SNYK repo scans, some have "high" and "critical" vulnerabilities, some don't:
Kserve repo: https://app.snyk.io/org/red-hat-openshift-data-science-rhods/projects?groupBy=targets&searchQuery=kserve&sortBy=highest+severity&filters[Show]=vuln-groups&filters[Integrations]=&before&after --> note: vulnerabilities in docs/ and python/ folder can be ignored as they are not used in production.
TGIS repo: https://app.snyk.io/org/red-hat-openshift-data-science-rhods/projects?groupBy=targets&searchQuery=text&sortBy=highest+severity&filters[Show]=vuln-groups&filters[Integrations]=&before&after
Caikit repos: https://app.snyk.io/org/red-hat-openshift-data-science-rhods/projects?groupBy=targets&searchQuery=caikit&sortBy=highest+severity&filters[Show]=vuln-groups&filters[Integrations]=&before&after
ModelMesh repos: https://app.snyk.io/org/red-hat-openshift-data-science-rhods/projects?groupBy=targets&searchQuery=model&sortBy=highest+severity&filters[Show]=vuln-groups&filters[Integrations]=&before&after
https://app.snyk.io/org/red-hat-openshift-data-science-rhods/projects?groupBy=targets&searchQuery=rest&sortBy=highest+severity&filters[Show]=vuln-groups&filters[Integrations]=&before&after

Quay images:
**quay.io/modh**
[kserve-storage-initializer](https://quay.io/repository/modh/kserve-storage-initializer?tab=tags)

**quay/opendatahub-io** --> for this, we probably should just do a rebuild because downstream (red-hat-data-services) already have updated images with no critical or high vulnerabilites except the `kserve-storage-initiliazer`
[kserve-storage-initializer](https://quay.io/repository/opendatahub/kserve-storage-initializer?tab=tags)
[kserve-alibi-explainer](https://quay.io/repository/opendatahub/kserve-alibi-explainer?tab=tags)
[kserve-art-explainer](https://quay.io/repository/opendatahub/kserve-art-explainer?tab=tags)
[caikit-tgis-serving](https://quay.io/repository/opendatahub/caikit-tgis-serving?tab=tags) --> fast tag needs an updated image

**Comment by heyselbi** [comment]
Current status:
KServe SNYK:
- 12 High in Code analysis
- 5 in `go.mod`

@Xaenalt should we deactivate the scanning of python/ folder? A lot of vulnerabilities come up there.

TGIS SNYK: none

Caikit SNYK: none

Modelmesh SNYK:
- 7 high in `go.mod` of `modelmesh-serving`
- 10 high in `go.mod` of `modelmesh-runtime-adapter`
- 3 high in `go.mod` of `rest-proxy`
- a lot in `openvino_model_server` --> need to deactivate the folders/files not used

Haven't checked the Quay images.

**Comment by Xaenalt** [comment]
The python/ folder is used for the storage-initializer, we need a few subfolders there sadly

**Comment by heyselbi** [comment]
@bdattoma Yes they are supposed be either fixed or addressed. @israel-hdez will be working on it.

**Comment by heyselbi** [comment]
Closing this issue as @Xaenalt PR addressing several KServe vulnerabilities is already included in RHODS 1.33. [Here](https://github.com/opendatahub-io/kserve/issues/91) is the follow up ticket for addressing the rest of the KServe issues.
