### ISSUE TITLE
kserve-controller-manager doesn't have enough CPU to run at scale

### ISSUE THREAD

**Issue by kpouget** [opendatahub-io/kserve#76]
*This ticket has been duplicated from https://github.com/opendatahub-io/opendatahub-operator/issues/499*.

**Describe the bug**
While running the KServe scale test, we observed that the `kserve-controller-manager` is unable to answer the queries in due time:
```
2023-08-30 10:33:43,425 p=1878 u=psap-ci-runner n=ansible | <stderr> Error from server (InternalError): 
- error when creating "/mnt/logs/004__watsonx_serving__deploy_model/src/inference_service.yaml": 
- Internal error occurred: failed calling webhook "inferenceservice.kserve-webhook-server.defaulter": 
failed to call webhook: 
- Post "[https://kserve-webhook-server-service.redhat-ods-applications.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s](https://kserve-webhook-server-service.redhat-ods-applications.svc/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s)": 
- context deadline exceeded
```

**To Reproduce**
1. Deploy a large number of models (300) in a short timeframe
2. Query the `InferenceService` objects regularly
3. Observe that the KServe webhook is unable to answer the requests 

**Expected behavior**
The KServe webhook is always able to answer the requests

**Additional context**
The issue likely comes from the low amount of CPU limit given to the `kserve-controller-manager`:
```
                        "resources": {
                            "limits": {
                                "cpu": "100m",
                                "memory": "300Mi"
                            },
                            "requests": {
                                "cpu": "100m",
                                "memory": "200Mi"
                            }
                        },
```

**Workaround**
I ran the same scale test with 
1. the RHODS operator turned off
2. the test passed with the CPU and memory limit increased to these values:
```
    rhods.operator.customize.kserve.cpu: 500m
    rhods.operator.customize.kserve.memory: 500Mi
```
```python
        run.run(f"oc get deploy/kserve-controller-manager -n redhat-ods-applications -ojson "
                f"| jq --arg mem '{mem}' --arg cpu '{cpu}' '.spec.template.spec.containers[0].resources.limits.cpu = $cpu | .spec.template.spec.containers[0].resources.limits.memory = $mem' "
                f"| oc apply -f-")
```

**Comment by Jooho** [comment]
This is the manifests : https://github.com/opendatahub-io/kserve/blob/master/config/default/manager_resources_patch.yaml#L13-L14

**Comment by Jooho** [comment]
https://github.com/opendatahub-io/kserve/issues/126
~~~
      - name: manager
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
~~~
