### ISSUE TITLE
After RHODS upgrade model serving component are back to using tags instead of digest

### ISSUE THREAD

**Issue by tarukumar** [opendatahub-io/kserve#78]
/kind bug
What steps did you take and what happened:
[A clear and concise description of what the bug is.]

1. Create a cluster
2. Install rhods 1.32 rc7 from embedded channel
3. Deploy Model and query it
4. Take nightly build from rhods 1.33 (17) and update the catalog
5. Wait for the Upgrade to be available
6. Approve the install plan and upgrade rhods
7. What did you expect to happen:
Model should respond without any issue

What's the InferenceService yaml:
[To help us debug please run kubectl get isvc $name -n $namespace -oyaml and paste the output]
`apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{"serving.knative.openshift.io/enablePassthrough":"true","sidecar.istio.io/inject":"true","sidecar.istio.io/rewriteAppHTTPProbers":"true"},"name":"flan-t5-small-caikit","namespace":"watsonx"},"spec":{"predictor":{"minReplicas":1,"model":{"modelFormat":{"name":"caikit"},"runtime":"caikit-runtime","storageUri":"s3://ods-ci-wisdom/flan-t5-small/"},"serviceAccountName":"models-bucket-sa"}}}
serving.knative.openshift.io/enablePassthrough: "true"
sidecar.istio.io/inject: "true"
sidecar.istio.io/rewriteAppHTTPProbers: "true"
creationTimestamp: "2023-09-04T12:56:57Z"
finalizers:

inferenceservice.finalizers
generation: 1
name: flan-t5-small-caikit
namespace: watsonx
resourceVersion: "73428"
uid: 27d2d5cd-c81e-4d9d-965e-3ef0e42eb0cb
spec:
predictor:
minReplicas: 1
model:
modelFormat:
name: caikit
name: ""
resources: {}
runtime: caikit-runtime
storageUri: s3://ods-ci-wisdom/flan-t5-small/
serviceAccountName: models-bucket-sa
status:
address:
url: http://flan-t5-small-caikit-predictor.watsonx.svc.cluster.local/
components:
predictor:
address:
url: http://flan-t5-small-caikit-predictor.watsonx.svc.cluster.local/
latestCreatedRevision: flan-t5-small-caikit-predictor-00001
latestReadyRevision: flan-t5-small-caikit-predictor-00001
latestRolledoutRevision: flan-t5-small-caikit-predictor-00001
traffic:
latestRevision: true
percent: 100
revisionName: flan-t5-small-caikit-predictor-00001
url: https://flan-t5-small-caikit-predictor-watsonx.apps.aerds-vw2-pool-srbls.gcp.rhods.ccitredhat.com/
conditions:
lastTransitionTime: "2023-09-04T13:09:35Z"
status: "True"
type: IngressReady
lastTransitionTime: "2023-09-04T13:09:34Z"
severity: Info
status: "True"
type: LatestDeploymentReady
lastTransitionTime: "2023-09-04T13:09:34Z"
severity: Info
status: "True"
type: PredictorConfigurationReady
lastTransitionTime: "2023-09-04T13:09:35Z"
status: "True"
type: PredictorReady
lastTransitionTime: "2023-09-04T13:09:35Z"
severity: Info
status: "True"
type: PredictorRouteReady
lastTransitionTime: "2023-09-04T13:09:35Z"
status: "True"
type: Ready
lastTransitionTime: "2023-09-04T13:09:35Z"
severity: Info
status: "True"
type: RoutesReady
modelStatus:
copies:
failedCopies: 0
totalCopies: 1
states:
activeModelState: Loaded
targetModelState: Loaded
transitionStatus: UpToDate
observedGeneration: 1
url: https://flan-t5-small-caikit-predictor-watsonx.apps.aerds-vw2-pool-srbls.gcp.rhods.ccitredhat.com/
`
Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
Environment:

Kiali: v1.65.7
Service Mesh:v2.4.2
KServe Controller: v0.11.0
Jager : v1.42.0-5+0.1687199951.p
Serverless: v1.29.1
Open Data Hub version:RHODS 2.2.0
Deployment Environment:[cloud (aws|gcp|ibm|azure), on prem, edge ] GCP
OpenShift version: (use kubectl version):
OS (e.g. from /etc/os-release):

**Comment by tarukumar** [comment]
After upgrade observed that kserve-controller image change from digest to tag;

Before(1.32):
quay.io/modh/kserve-controller@sha256:87876990f0c65080ba9b62c4f71a09e2501e795b1366473d5ab89742aef4fabb

After: (1.33)
quay.io/opendatahub/kserve-controller:v0.11.0

![image](https://github.com/opendatahub-io/kserve/assets/93319437/267f8f82-f918-4cad-a3fb-f564b2a0b60b)


[takumar@fedora Downloads]$ oc get installplan -n redhat-ods-operator NAME            CSV                    APPROVAL    APPROVED install-6sp5h   rhods-operator.2.1.0   Automatic   true install-rfb5z   rhods-operator.2.2.0   Manual      true

**Comment by tarukumar** [comment]
@israel-hdez @Jooho FYI

**Comment by israel-hdez** [comment]
We are still figuring out our workflow to ensure the right tags are in place for releases. Nighties are, perhaps, a little bit different situation. cc @heyselbi 

I'll check-out with the team tomorrow in an afternoon meeting.

On the understanding that this is RHOAI nighties (and _not_ ODH nighties), perhaps, for now, expect the right SHAs to _eventually_ be in place after the `1.33` branch cut.

**Comment by israel-hdez** [comment]
`1.33` images should be correctly set now.
