### ISSUE TITLE
SPIKE: Investigate deploying ensemble models using InferenceGraphs

### ISSUE THREAD

**Issue by VedantMahabaleshwarkar** [opendatahub-io/kserve#84]
Kserve allows model chaining via `InferenceGraphs`. 
The Kserve documentation has some examples of InferenceGraphs : 
https://github.com/kserve/kserve/tree/master/docs/samples/graph 
https://kserve.github.io/website/master/modelserving/inference_graph/image_pipeline/  

We need to figure out how to support InferenceGraphs using Kserve in ODH and provide the correct documentation for the creation of the InferenceGraph as well as documentation for how to do rest inferencing against the graph

**Comment by israel-hdez** [comment]
Migrated to https://issues.redhat.com/browse/RHOAIENG-2950

/close
