### ISSUE TITLE
Dependent Operators(Serverless/ServiceMesh) Manifests Delivery Method

### ISSUE THREAD

**Issue by Jooho** [opendatahub-io/kserve#89]
/kind feature

**Describe the solution you'd like**
Dependent operators will be installed by users and they will follow a document. We need to work with the doc team member(John Byrne).
Target operators:
- Serverless
- Service Mesh 2.0

**Anything else you would like to add:**

**Comment by heyselbi** [comment]
cc @jbyrne-redhat

**Comment by Jooho** [comment]
PR: https://github.com/opendatahub-io/opendatahub-operator/pull/691
DOC: [KServe install of dependencies](https://docs.google.com/document/d/1pf0x1geayFr-06lAQKr96ynVsnOCcpgmAfbgoHgg8AI/edit)

**Comment by Jooho** [comment]
Doc included this operation installation part so I will close this ticket.
