### ISSUE TITLE
Follow-up: Address remaining "High" vulnerabilities in KServe repo from SNYK scans

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#91]
[SNYK scan](https://app.snyk.io/org/red-hat-openshift-data-science-rhods/projects?groupBy=targets&searchQuery=kserve&sortBy=highest+severity&filters%5BShow%5D=vuln-groups&filters%5BIntegrations%5D=&before&after&fromGitHubAuth=true) of KServe repo

- [ ] Deactivate files in `/python` directory that are not used in the build
- [x] Address high vulnerabilities in `/python` directory that are used in the build, if any (perhaps one in `/python/kserve/`?)
- [x] Address high vulnerabilities in `Code analysis`
- [x] Address high vulnerabilities in `go.mod`

**Comment by heyselbi** [comment]
SNYK also creates automatic PRs which might be of use:
https://github.com/red-hat-data-services/kserve/pulls

**Comment by israel-hdez** [comment]
I cannot deactivate the other python entries that we are not using.

Deactivating does not remove from the list... Maybe we can keep as is, since those still will introduce noise?

**Comment by israel-hdez** [comment]
Upstream PR: https://github.com/kserve/kserve/pull/3157

**Comment by heyselbi** [comment]
Downstream commit that is part of rhods 1.34: https://github.com/red-hat-data-services/kserve/commit/820006e415491d6d7858be82c5743c42529cffc5 

Closing the issue. The kserve upstream issue, whenever it is merged, will be part of new kserve release.

**Comment by bdattoma** [comment]
>I cannot deactivate the other python entries that we are not using.

If these files are note used, could they be deleted? @israel-hdez 

What about `docs/apis/Dockerfile`? it's in docs, but it's still a Dockerfile. Is it used or intended to be used by someone else?

**Comment by israel-hdez** [comment]
https://kserve.github.io/website/0.11/reference/api/

> > I cannot deactivate the other python entries that we are not using.
> 
> If these files are not used, could they be deleted? @israel-hdez
> 

My rationale for not deleting, is that upstream community DO use that code and they maintain it.

We could delete these files, but by doing so we introduce a point of conflict; i.e. `git` will constantly complain with "_we deleted, theirs modified_" and will ask for manual conflict resolution. So, code syncs with upstream repos will become less automatable.

> What about `docs/apis/Dockerfile`? it's in docs, but it's still a Dockerfile. Is it used or intended to be used by someone else?

I'm not fully familiar with all the code base. My guess is that this Dockerfile is used to generate this reference documentation: https://github.com/kserve/website/blob/main/docs/reference/api.md, which is the source for this web-doc: https://kserve.github.io/website/0.11/reference/api/. If my guess is right, the vulnerabilities are not a concern, because the deliverable artifact is the `md` file (which is just plain text) and the container image is just _developer tooling_.

**Comment by bdattoma** [comment]
> https://kserve.github.io/website/0.11/reference/api/
> 
> > > I cannot deactivate the other python entries that we are not using.
> > 
> > 
> > If these files are not used, could they be deleted? @israel-hdez
> 
> My rationale for not deleting, is that upstream community DO use that code and they maintain it.
> 
> We could delete these files, but by doing so we introduce a point of conflict; i.e. `git` will constantly complain with "_we deleted, theirs modified_" and will ask for manual conflict resolution. So, code syncs with upstream repos will become less automatable.
> 
> > What about `docs/apis/Dockerfile`? it's in docs, but it's still a Dockerfile. Is it used or intended to be used by someone else?
> 
> I'm not fully familiar with all the code base. My guess is that this Dockerfile is used to generate this reference documentation: https://github.com/kserve/website/blob/main/docs/reference/api.md, which is the source for this web-doc: https://kserve.github.io/website/0.11/reference/api/. If my guess is right, the vulnerabilities are not a concern, because the deliverable artifact is the `md` file (which is just plain text) and the container image is just _developer tooling_.

understood. So, our downstream image doesn't contain these files right?

**Comment by israel-hdez** [comment]
> 
> understood. So, our downstream image doesn't contain these files right?

That's right.

I just want to stress that files under `python/kserve` _are_ in downstream, and I fixed issues under this path. And, well, anything under `docs/` is not present in our images.

**Comment by bdattoma** [comment]
got it, thank you for the clarifications @israel-hdez
