### ISSUE TITLE
[DEV TRACKER] Model Serving Requirements for Q4

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/kserve#92]
### Req 1: Model Storage
Users must be able to to deploy a model stored in (d.) AWS
- https://github.com/opendatahub-io/modelmesh-serving/issues/113

### Req 2: Model Formats - Estimate: RHODS 1.36
Users must be able to serve models based on a variety of framework (a.) OOTB support for TensorFlow, PyTorch, scikit-learn models and (d.) Users must be able to serve models from Hugging Face without having to do any additional conversions or configurations 
- https://github.com/opendatahub-io/kserve/issues/86

### Req 7: Deployment Rollouts
a. Ability to deploy new model versions & deploy % of traffic to new version (canary rollout)
b. Ability to do A/B testing on different model versions
c.  Ability to test deployed endpoint directly in the product UI
- https://github.com/opendatahub-io/kserve/issues/98

### Req 10: OOTB Deployed model performance metrics
Users must be able to access performance metrics for all deployed models (e.) CPU/GPU/memory utilization
- https://github.com/opendatahub-io/kserve/issues/99

### Req 14: Model Serving Runtimes
b. OOTB support for Caikit/TGIS
- https://github.com/opendatahub-io/caikit/issues/11 - RHODS 1.35
- https://github.com/opendatahub-io/caikit/issues/13

c. OOTB support for NVIDIA Triton Inference Server
- https://github.com/opendatahub-io/modelmesh-serving/issues/184

### Req 15: Remote Deployment
eg. locations other than the cluster where model deployment is initiated (a.) Support models being deployed to remote (location other than where model deployment is initiated)
- https://github.com/opendatahub-io/modelmesh-serving/issues/185
- https://github.com/opendatahub-io/caikit/issues/12

### Req 17: Support options for KServe and/or ModelMesh - Estimate: RHODS 1.36
Support KServe - 1 model per pod or modelmesh - multiple models per pod (a.) RHODS admins should be able to configure whether they want to use KServe (single model serving + additional functionality), ModelMesh, or both
- https://github.com/opendatahub-io/modelmesh-serving/issues/193
- https://github.com/opendatahub-io/opendatahub-operator/issues/573
- https://github.com/opendatahub-io/modelmesh-serving/issues/186

## Other planned features
- https://github.com/opendatahub-io/modelmesh-serving/issues/207 - RHODS 1.35
- https://github.com/opendatahub-io/caikit/issues/15 - RHODS 1.36
- https://github.com/opendatahub-io/odh-model-controller/issues/61 - RHODS 1.36

## Other planned enhancements
- https://github.com/opendatahub-io/modelmesh-serving/issues/137 - RHODS 1.35
- https://github.com/opendatahub-io/modelmesh-serving/issues/228 - RHODS 1.35
- https://github.com/opendatahub-io/modelmesh-serving/issues/192 - RHODS 1.35

## Other planned bug fixes
- https://github.com/opendatahub-io/kserve/issues/77 - RHODS 1.35
- https://github.com/opendatahub-io/odh-model-controller/issues/86 - RHODS 1.35

#### Resources
Model Serving Phase 2 Requirements [doc](https://docs.google.com/document/d/1TXLEyzpYX6inMHOlaUW8VbMxMvQ5Y9TEzHM87G9_1Yk/edit)
Model Serving Phase 2 Requirement Mapping [spreadsheet](https://docs.google.com/spreadsheets/d/1GRwEm9Pvy6aakhukEuu2DXMg9Mjte1V9YPZSCSfOLE0/edit#gid=0)

**Comment by israel-hdez** [comment]
Closing, as we are now tracking work on Jira.
