### ISSUE TITLE
Change in domain templates

### ISSUE THREAD

**Issue by bartoszmajsak** [opendatahub-io/kserve#96]
/kind feature

**Describe the solution you'd like**
We would like to have an enhancement to the domain template used in KServe. Currently, it's defined as `{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}`. 

Changing it to `{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}` will make the `AuthConfig`s more specific, allowing for the creation of a configuration for `*.{{.Namespace}}` directly instead of monitoring all models and creating new "hosts".

**Comment by Jooho** [comment]
@bartoszmajsak To be clear what we should do with this ticket, I have some questions.
is this request to change this configuraton:https://github.com/opendatahub-io/kserve/blob/master/config/configmap/inferenceservice.yaml#L181 to `{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}`  for AuthConfig?

**Comment by bartoszmajsak** [comment]
> @bartoszmajsak To be clear what we should do with this ticket, I have some questions. is this request to change this configuraton:[`master`/config/configmap/inferenceservice.yaml#L181](https://github.com/opendatahub-io/kserve/blob/master/config/configmap/inferenceservice.yaml?rgh-link-date=2023-10-03T11%3A55%3A50Z#L181) to `{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}` for AuthConfig?

Technically speaking more about this https://github.com/opendatahub-io/kserve/blob/b6eac44afc395f864f10ee77c3d0a5636d9c1575/config/configmap/inferenceservice.yaml#L451 #88 

@aslakknutsen can you confirm?

**Comment by aslakknutsen** [comment]
`domainTemplate`is part of the KServe configuration. On the Authorino side we canonly bind AuthConfigs to "hosts" with wildcard levels(*.x.y), not partly wildcards(*-x.y).

This change would allow us to handle 1 domain pattern between all models in a odh-project(namespace) without the need for additional listeners to update the host lists or filters to manipulate the  incoming host name.

**Comment by aslakknutsen** [comment]
> @aslakknutsen can you confirm?

Not 100% sure of the source of this configuration in the kserve world and how that is moved to osd-manifests etc, but that certainly would look like it.

**Comment by israel-hdez** [comment]
@aslakknutsen @bartoszmajsak Do you need to change only the `InferenceService` public domain? Or would you also need a similar change to the domain of the KNative services?

**Comment by israel-hdez** [comment]
@aslakknutsen In KServe, when you create an InferenceService, it creates KNative services for you to deploy the models.

The `ksvc`s can also be publicly exposed with their own URL with a similar pattern that also seems to be `{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}` by default.

So, several routes can be involved:
1. The route for the ISVC itself.
2. But we can also have several KNative routes.

My understanding is that you would want (1) changed, but not sure if routes in (2) would be relevant.

In any case, I was looking at doc comments in the inferenceservice-config ConfigMap, and it looks like the template is only applicable to `RawDeployment` which, at the moment, we are not using. See: https://github.com/opendatahub-io/kserve/blob/799e12122f4b6d3ca85f67f145706df6d43ffa18/config/configmap/inferenceservice.yaml#L215-L223.

I haven't tested, but from those doc comments, my understanding is that changing that template won't have any impact on the generated URLs for KServe Serverless installation. It seems that KNative is the component that is controlling the URL template. However, I couldn't find any docs for configuring KNative's URL template.

So, my perception is that is not as easy as changing the template. It may be an enhancement that needs to be done to KServe.
